name: Build Docker Image and Jupyter Notebooks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ["*.*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        # if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .ci/Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
  run-code:
    needs: docker
    strategy:
      matrix:
        notebook:
          - index.ipynb
          - ch01-01-first-steps.ipynb
          - ch01-02-sde.ipynb
          - ch01-03-ensemble.ipynb
          - ch01-04-paramestim.ipynb
          - ch01-05-callback.ipynb
          - ch02-01-symbolics.ipynb
          - ch02-02-modelingptoolkit.ipynb
          - ch02-03-catalyst.ipynb
          - ch02-04-pde.ipynb
          - ch03-01-neuron.ipynb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        # if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .ci/Dockerfile
          load: true
          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha

      - name: Build Notebooks
        run: docker run -v ${{ github.workspace }}:/work ${{ env.IMAGE_NAME }}:test jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace /work/docs/${{ matrix.notebook }}

  jupyter-book:
    needs: [run-code, docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,priority=600, event=pr
            type=ref,priority=600, event=tag
            type=raw,value=latest,priority=600, enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
          flavor: |
            latest=false
      - name: Build Docker Image
        # if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .ci/Dockerfile
          load: true
          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha

      - name: Build website
        run: docker run -v ${{ github.workspace }}:/work ${{ env.IMAGE_NAME }}:test jupyter-book build /work/docs -vvv

      - name: Push Docker Image
        # Do not push on PR's
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .ci/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Deploy Website
      #   uses: peaceiris/actions-gh-pages@v3.8.0
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     force_orphan: true
      #     publish_dir: docs/_build/html
      #     full_commit_message: ${{ github.event.head_commit.message }}
